name: Helloworld
on:
  workflow_dispatch:
env:
  MY_VAR: ${{ DEMO_SECRET }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Variable get action
        run: echo "Hello, World! $MY_VAR"

